#trivial - Eslint rule style addition - class variables
justeat/eslint-config-fozzie pull request #48
Opened 2021-11-25 12:48 UTC by oliversweb

### Added
- Extended the project eslint rule file to cover class variables
---
https://eslint.org/docs/rules/lines-between-class-members

2021-11-25 12:59 UTC, kevinrodrigues approved these changes

2021-11-25 13:01 UTC, kevinrodrigues requested changes

2021-11-25 13:01 UTC, kevinrodrigues commented on rules/style.js
> +        'lines-between-class-members': [
Need the package version && changelog too.

2021-11-25 13:55 UTC, kevinrodrigues submitted a review, later dismissed

2021-11-25 14:00 UTC, DamianMullins commented on rules/style.js
> +        // class specfic styles
Minor thing but the rules in these files look to be alphabetical which does make life easier when you're adding a load of the rules and aren't sure where to place them in the module (I'm guessing makes it easier to find a particular rule?). If you want to create a new section for classes maybe we could create a new module?

2021-11-25 14:54 UTC, kevinrodrigues approved these changes

2021-11-25 15:23 UTC, DamianMullins submitted a review, later dismissed

2021-11-29 16:40 UTC, ashleynolan approved these changes

2021-12-01 11:19 UTC, ashleynolan requested changes
Just ran a couple of the build checks locally (as it looks like this hooks up to travis which isn't running) – looks like running `yarn lint` on this throws up a few errors (minor things).

Could you fix these?

2021-12-07 15:08 UTC, ashleynolan commented
I've updated the linting rules now for this – going to look to see if I can switch the build on Circle shortly too so this runs automatically.

2021-12-08 13:53 UTC, merged